import { readFileSync } from "node:fs";
import { Ajv, type ErrorObject } from "ajv";
import { describe, expect, it } from "vitest";

import {
  CLIENT_NOTIFICATIONS,
  CLIENT_REQUESTS,
  SERVER_NOTIFICATIONS,
  SERVER_REQUESTS,
} from "../src/protocol.js";
import {
  clientNotifications,
  clientRequests,
  serverRequestResponses,
} from "./fixtures/app-server.js";

// the schema dir is regenerated by `npm run pretest` from the installed codex cli,
// so every assertion below runs against the real protocol, not a hand-written copy
const schemaDir = new URL("../schema/", import.meta.url);

interface MethodVariant {
  properties?: { method?: { const?: string; enum?: string[] } };
}
interface UnionSchema {
  definitions?: Record<string, unknown>;
  oneOf?: MethodVariant[];
  anyOf?: MethodVariant[];
}

function loadSchema<T = UnionSchema>(file: string): T {
  return JSON.parse(readFileSync(new URL(file, schemaDir), "utf8")) as T;
}

// the generator writes each method as a single-element enum; accept const too in case that changes
function methodOf(variant: MethodVariant): string | undefined {
  const method = variant.properties?.method;
  return method?.const ?? (method?.enum?.length === 1 ? method.enum[0] : undefined);
}

function variantsOf(schema: UnionSchema): MethodVariant[] {
  return schema.oneOf ?? schema.anyOf ?? [];
}

function methodNames(schema: UnionSchema): Set<string> {
  const names = new Set<string>();
  for (const variant of variantsOf(schema)) {
    const name = methodOf(variant);
    if (name !== undefined) names.add(name);
  }
  return names;
}

// strict:false lets ajv accept the generated draft-07 bundle (unknown formats such as "uint", "int64"),
// and logger:false keeps those unknown-format notices out of the test output
const ajv = new Ajv({ strict: false, allErrors: true, logger: false });

function expectValid(schema: object, file: string, value: unknown): void {
  const validate = ajv.compile(schema);
  const ok = validate(value);
  const errors = (validate.errors ?? []) as ErrorObject[];
  expect(ok, `${file} rejected ${JSON.stringify(value)}:\n${ajv.errorsText(errors, { separator: "\n" })}`).toBe(true);
}

function assertValid(file: string, value: unknown): void {
  expectValid(loadSchema<object>(file), file, value);
}

// validating against the matching variant instead of the whole union keeps failure output readable
function assertValidVariant(file: string, value: { method: string }): void {
  const schema = loadSchema(file);
  const variant = variantsOf(schema).find((v) => methodOf(v) === value.method);
  expect(variant, `${file} has no variant for method ${value.method}`).toBeDefined();
  expectValid({ definitions: schema.definitions, ...variant }, file, value);
}

describe("protocol method names exist in the generated app-server schema", () => {
  const cases: Array<[string, Record<string, string>]> = [
    ["ClientRequest.json", CLIENT_REQUESTS],
    ["ClientNotification.json", CLIENT_NOTIFICATIONS],
    ["ServerNotification.json", SERVER_NOTIFICATIONS],
    ["ServerRequest.json", SERVER_REQUESTS],
  ];

  for (const [file, names] of cases) {
    it(`${file} declares every name in protocol.ts`, () => {
      const known = methodNames(loadSchema(file));
      expect(known.size).toBeGreaterThan(0);
      for (const name of Object.values(names)) {
        expect(known, `${name} is missing from ${file}`).toContain(name);
      }
    });
  }
});

describe("protocol.ts declares every ServerRequest variant the schema knows about", () => {
  it("SERVER_REQUESTS is not missing a method the schema declares", () => {
    // the reverse of the check above: a new schema-declared ServerRequest variant that
    // protocol.ts hasn't picked up wouldn't fail the drift alarm without this direction too
    const known = methodNames(loadSchema("ServerRequest.json"));
    const declared = new Set(Object.values(SERVER_REQUESTS));
    expect(known.size).toBeGreaterThan(0);
    for (const name of known) {
      expect(declared, `${name} is declared in ServerRequest.json but missing from SERVER_REQUESTS`).toContain(name);
    }
  });
});

describe("client request fixtures validate against ClientRequest.json", () => {
  for (const [key, request] of Object.entries(clientRequests)) {
    it(`${key} (${request.method})`, () => {
      const message = { id: 1, ...request };
      assertValidVariant("ClientRequest.json", message);
      assertValid("ClientRequest.json", message);
    });
  }
});

describe("client notification fixtures validate against ClientNotification.json", () => {
  for (const [key, notification] of Object.entries(clientNotifications)) {
    it(`${key} (${notification.method})`, () => {
      assertValid("ClientNotification.json", notification);
    });
  }
});

describe("responses to server requests validate against their response schema", () => {
  for (const [method, { schema, response }] of Object.entries(serverRequestResponses)) {
    it(`${method} -> ${schema}`, () => {
      expect(Object.values(SERVER_REQUESTS)).toContain(method);
      assertValid(schema, response);
    });
  }
});
